name: 'Create Homebrew PR'
on:
  push:
    tags:
      - 'v*'
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: autocorrect
          formula-path: Formula/a/autocorrect.rb
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
